name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
        postgres:
          image: postgres:11
          env:
            POSTGRES_USER: misago
            POSTGRES_PASSWORD: misago
            POSTGRES_DB: misago
          ports:
            - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements-dev.txt
      - name: Test with pytest
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          MISAGO_DATABASE_URL: postgresql://misago:misago@localhost/misago
          MISAGO_CACHE_URL: locmem://0
          MISAGO_PUBSUB_URL: memory://
          MISAGO_STATIC_ROOT: /app/media
          MISAGO_MEDIA_ROOT: /app/static
        run: |
          pytest --cov=misago
          coveralls